export type Size = "XS" | "S" | "M" | "L" | "XL";
export const sizesOrdered: Size[] = ["XS", "S", "M", "L", "XL"]

export interface Product {
  imgUrl: string,
  name: string,
  description: string,
  category: string,
  materials: string,
  price: number,
  size: Size
  inStock: number,
}

export function emptyProduct() {
  return {
    imgUrl: null,
    name: "",
    description: "",
    category: "",
    materials: "",
    price: 0,
    size: undefined,
    inStock: 0,
  }
}

export const products: Product[] = [
  {
    imgUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
    name: "Classic Denim Jacket",
    description: "A timeless denim jacket for casual outings.",
    category: "Jackets",
    materials: "100% Cotton",
    price: 59.99,
    size: "L",
    inStock: 60,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Cotton T-Shirt",
    description: "Soft and comfortable cotton t-shirt.",
    category: "T-Shirts",
    materials: "100% Organic Cotton",
    price: 19.99,
    size: "M",
    inStock: 60,
  },
  {
    imgUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
    name: "Running Saneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "L",
    inStock: 30,
  },
  {
    imgUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
    name: "Running Sn2eakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "L",
    inStock: 30,
  },
  {
    imgUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
    name: "Running Sne2akers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "S",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Running Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run1ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run2ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run3ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run4ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run5ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run6ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run7ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run8ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
  {
    imgUrl: "https://m.media-amazon.com/images/I/61dExu1GuhL._AC_UY1000_.jpg",
    name: "Run9ning Sneakers",
    description: "Perfect for daily runs or casual wear.",
    category: "Shoes",
    materials: "Mesh, Rubber",
    price: 79.99,
    size: "XS",
    inStock: 30,
  },
];
